apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins
spec:
  type: NodePort # Change to LoadBalancer if using cloud providers
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30000 # Adjust as needed
  selector:
    app: jenkins
